version: "2"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        image: org/web
        links:
            - db
        cpu_shares: 300
        mem_limit: 512m
        environment:
            DatabaseServer: "db"
            DatabaseName: "StudentsDb"
            DatabaseUser: "sa"
            DatabaseUserPassword: "Password1!"
    db:
        image: "microsoft/mssql-server-linux"
        cpu_shares: 300
        mem_limit: 1024m
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password1!"
            ACCEPT_EULA: "Y"